"""
SENTINEL — Tool Gateway: Sandbox & Export
FR6.2-6.4: Code execution, document generation (docx/xlsx/pptx).
Section 3.7: Hardened sandbox for code execution.
"""
from __future__ import annotations

import asyncio
import json
import logging
import subprocess
import tempfile
import uuid
from pathlib import Path

from src.shared.config import get_settings

logger = logging.getLogger(__name__)
settings = get_settings()


class SandboxExecutor:
    """
    Hardened code execution sandbox (Section 3.7).
    In development: subprocess with resource limits.
    In production: Docker container with --network none, cap-drop=ALL, etc.
    """

    async def execute(
        self,
        code: str,
        language: str = "python",
        timeout: int = 30,
    ) -> str:
        """Execute code in a sandboxed environment."""
        if language == "python":
            return await self._execute_python(code, timeout)
        else:
            return f"Language '{language}' not supported yet"

    async def _execute_python(self, code: str, timeout: int = 30) -> str:
        """Execute Python code with resource limits."""
        with tempfile.NamedTemporaryFile(mode="w", suffix=".py", delete=False) as f:
            f.write(code)
            f.flush()
            temp_path = f.name

        try:
            process = await asyncio.create_subprocess_exec(
                "python3", temp_path,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
            stdout, stderr = await asyncio.wait_for(
                process.communicate(),
                timeout=timeout,
            )

            output = stdout.decode("utf-8", errors="replace")
            errors = stderr.decode("utf-8", errors="replace")

            if process.returncode == 0:
                return f"Exit code: 0\nOutput:\n{output}"
            else:
                return f"Exit code: {process.returncode}\nOutput:\n{output}\nErrors:\n{errors}"
        except asyncio.TimeoutError:
            return "Error: Code execution timed out"
        except Exception as e:
            return f"Error: {e}"
        finally:
            Path(temp_path).unlink(missing_ok=True)


class ExportService:
    """
    Document export engines (FR6.2-6.4).
    python-docx, openpyxl, python-pptx with verification.
    """

    async def create_document(
        self,
        doc_type: str,
        content: str,
        task_id: str,
        title: str = "SENTINEL Generated Document",
        metadata: dict | None = None,
    ) -> str:
        """Create a document and return the file path."""
        output_dir = settings.artifact_store_path / task_id
        output_dir.mkdir(parents=True, exist_ok=True)

        if doc_type == "docx":
            return await self._create_docx(content, title, output_dir, metadata)
        elif doc_type == "xlsx":
            return await self._create_xlsx(content, title, output_dir, metadata)
        elif doc_type == "pptx":
            return await self._create_pptx(content, title, output_dir, metadata)
        else:
            raise ValueError(f"Unsupported document type: {doc_type}")

    async def _create_docx(
        self,
        content: str,
        title: str,
        output_dir: Path,
        metadata: dict | None = None,
    ) -> str:
        """Create a Word document with provenance metadata."""
        from docx import Document
        from docx.shared import Inches, Pt
        from docx.enum.text import WD_ALIGN_PARAGRAPH

        doc = Document()

        # Title
        title_para = doc.add_heading(title, level=0)
        title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Generated by notice
        notice = doc.add_paragraph()
        notice.add_run("Generated by SENTINEL — Sovereign AI Workbench").italic = True
        notice.alignment = WD_ALIGN_PARAGRAPH.CENTER

        doc.add_paragraph()  # Spacer

        # Content — split into paragraphs
        for para_text in content.split("\n"):
            if para_text.strip():
                if para_text.startswith("# "):
                    doc.add_heading(para_text[2:], level=1)
                elif para_text.startswith("## "):
                    doc.add_heading(para_text[3:], level=2)
                elif para_text.startswith("### "):
                    doc.add_heading(para_text[4:], level=3)
                elif para_text.startswith("- "):
                    doc.add_paragraph(para_text[2:], style="List Bullet")
                else:
                    doc.add_paragraph(para_text)

        # Provenance footer
        doc.add_paragraph()
        footer = doc.add_paragraph()
        footer.add_run("— Document provenance tracked by SENTINEL Artifact Manager —").italic = True
        footer.alignment = WD_ALIGN_PARAGRAPH.CENTER

        filename = f"{uuid.uuid4().hex[:8]}_{title.replace(' ', '_')[:50]}.docx"
        filepath = output_dir / filename
        doc.save(str(filepath))

        return str(filepath)

    async def _create_xlsx(
        self,
        content: str,
        title: str,
        output_dir: Path,
        metadata: dict | None = None,
    ) -> str:
        """Create an Excel spreadsheet (FR6.2 — with recalculation pipeline)."""
        from openpyxl import Workbook
        from openpyxl.styles import Font, Alignment, PatternFill

        wb = Workbook()
        ws = wb.active
        ws.title = "Summary"

        # Title
        ws["A1"] = title
        ws["A1"].font = Font(bold=True, size=14)

        ws["A2"] = "Generated by SENTINEL"
        ws["A2"].font = Font(italic=True, size=10)

        # Parse content into rows
        rows = content.strip().split("\n")
        for i, row in enumerate(rows, start=4):
            cells = row.split(",") if "," in row else row.split("\t") if "\t" in row else [row]
            for j, cell_value in enumerate(cells):
                cell = ws.cell(row=i, column=j + 1, value=cell_value.strip())

        # Auto-size columns
        for col in ws.columns:
            max_length = max(len(str(cell.value or "")) for cell in col)
            ws.column_dimensions[col[0].column_letter].width = min(max_length + 4, 50)

        filename = f"{uuid.uuid4().hex[:8]}_{title.replace(' ', '_')[:50]}.xlsx"
        filepath = output_dir / filename
        wb.save(str(filepath))

        # FR6.2 — LibreOffice headless recalculation (if available)
        try:
            subprocess.run(
                ["soffice", "--headless", "--calc", "--convert-to", "xlsx", str(filepath)],
                capture_output=True, timeout=30, cwd=str(output_dir),
            )
            logger.info(f"Excel recalculated via LibreOffice: {filepath}")
        except (FileNotFoundError, subprocess.TimeoutExpired):
            logger.warning("LibreOffice not available for Excel recalculation")

        return str(filepath)

    async def _create_pptx(
        self,
        content: str,
        title: str,
        output_dir: Path,
        metadata: dict | None = None,
    ) -> str:
        """Create a PowerPoint presentation."""
        from pptx import Presentation
        from pptx.util import Inches, Pt

        prs = Presentation()

        # Title slide
        slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(slide_layout)
        slide.shapes.title.text = title
        slide.placeholders[1].text = "Generated by SENTINEL — Sovereign AI Workbench"

        # Content slides — split by sections
        sections = content.split("\n\n")
        for section in sections:
            if not section.strip():
                continue
            slide_layout = prs.slide_layouts[1]  # Title and Content
            slide = prs.slides.add_slide(slide_layout)
            lines = section.strip().split("\n")
            if lines:
                slide.shapes.title.text = lines[0].replace("# ", "").replace("## ", "")
                body = slide.placeholders[1]
                body.text = "\n".join(lines[1:]) if len(lines) > 1 else ""

        filename = f"{uuid.uuid4().hex[:8]}_{title.replace(' ', '_')[:50]}.pptx"
        filepath = output_dir / filename
        prs.save(str(filepath))

        return str(filepath)


# Singletons
sandbox_executor = SandboxExecutor()
export_service = ExportService()
